version: 1
runtime: go
api_version: go1

includes:
- secrets.yaml

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "service_account.json"

handlers:
- url: /spinner\.gif
  static_files: spinner.gif
  upload: spinner.gif
  secure: always
- url: /share
  login: admin
  secure: always
  script: _go_app
- url: /.*
  secure: always
  script: _go_app
